### Get all users
curl -X GET http://localhost:3000/users

### Create a user
curl -X POST http://localhost:3000/users \
-H "Content-Type: application/json" \
-d '{
    "name": "Customer Tester",
    "email": "customer.tester@app.com",
    "age": 14
}'

### Get a user by id
curl -X GET http://localhost:3000/users/684817a14a2bec99170315dd

### Delete a user by id
curl -X DELETE http://localhost:3000/users/684817a14a2bec99170315dd
