### Me
curl -X GET http://localhost:3000/users/me \
  --cookie "
    accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODQ4MmUyMmViZTllYWJmZjMyMGY5NDIiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0OTU2ODA1NSwiZXhwIjoxNzQ5NTY4MDg1fQ.ooUrE_ZqtrNOG-RJiBtrncaK4sSasZqgqAiKdhEWHKc;
    refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODQ4MmUyMmViZTllYWJmZjMyMGY5NDIiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0OTU2OTU1NSwiZXhwIjoxNzQ5NTY5Njc1fQ.RlK2zyncX993AUJ0MvHcka3mbBDehJeKnj2hz7Nxie8;
    "